/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const PreferredDApp = IDL.Record({
  'id' : IDL.Nat,
  'friendlyName' : IDL.Text,
  'canisterId' : IDL.Text,
});
export const Rule = IDL.Record({ 'id' : IDL.Nat, 'text' : IDL.Text });
export const Preferences = IDL.Record({
  'notes' : IDL.Text,
  'dApps' : IDL.Vec(PreferredDApp),
  'rules' : IDL.Vec(Rule),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const WorkflowId = IDL.Nat;
export const Owner = IDL.Principal;
export const Timestamp = IDL.Int;
export const Workflow = IDL.Record({
  'id' : WorkflowId,
  'owner' : Owner,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'updatedAt' : Timestamp,
  'planText' : IDL.Text,
  'favorite' : IDL.Bool,
});
export const HistoryId = IDL.Nat;
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const ChatRole = IDL.Variant({
  'user' : IDL.Null,
  'assistant' : IDL.Null,
});
export const ChatMessage = IDL.Record({
  'content' : IDL.Text,
  'role' : ChatRole,
  'timestamp' : Timestamp,
});
export const Conversation = IDL.Record({ 'messages' : IDL.Vec(ChatMessage) });
export const PlanResult = IDL.Record({ 'planText' : IDL.Text });
export const HistoryEntry = IDL.Record({
  'id' : HistoryId,
  'owner' : Owner,
  'goal' : IDL.Text,
  'createdAt' : Timestamp,
  'planText' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'addDApp' : IDL.Func([IDL.Text, IDL.Text], [Preferences], []),
  'addRule' : IDL.Func([IDL.Text], [Preferences], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createWorkflow' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text, IDL.Bool],
      [Workflow],
      [],
    ),
  'deleteDApp' : IDL.Func([IDL.Nat], [Preferences], []),
  'deleteHistoryEntry' : IDL.Func([HistoryId], [IDL.Bool], []),
  'deleteRule' : IDL.Func([IDL.Nat], [Preferences], []),
  'deleteWorkflow' : IDL.Func([WorkflowId], [IDL.Bool], []),
  'duplicateWorkflow' : IDL.Func([WorkflowId], [IDL.Opt(Workflow)], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'exportWorkflowMarkdown' : IDL.Func(
      [WorkflowId],
      [IDL.Opt(IDL.Text)],
      ['query'],
    ),
  'generatePlan' : IDL.Func([IDL.Text, Conversation], [PlanResult], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getHistoryEntry' : IDL.Func([HistoryId], [IDL.Opt(HistoryEntry)], ['query']),
  'getPreferences' : IDL.Func([], [IDL.Opt(Preferences)], ['query']),
  'getWorkflow' : IDL.Func([WorkflowId], [IDL.Opt(Workflow)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isOpenAIConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'listHistory' : IDL.Func([], [IDL.Vec(HistoryEntry)], ['query']),
  'listWorkflows' : IDL.Func([], [IDL.Vec(Workflow)], ['query']),
  'refinePlan' : IDL.Func([IDL.Text, Conversation], [PlanResult], []),
  'savePreferences' : IDL.Func([Preferences], [Preferences], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'searchWorkflows' : IDL.Func([IDL.Text], [IDL.Vec(Workflow)], ['query']),
  'setNotes' : IDL.Func([IDL.Text], [Preferences], []),
  'setOpenAIApiKey' : IDL.Func([IDL.Text], [], []),
  'toggleFavorite' : IDL.Func([WorkflowId], [IDL.Opt(Workflow)], []),
  'updateDApp' : IDL.Func([PreferredDApp], [Preferences], []),
  'updateRule' : IDL.Func([Rule], [Preferences], []),
  'updateWorkflow' : IDL.Func([Workflow], [IDL.Opt(Workflow)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const PreferredDApp = IDL.Record({
    'id' : IDL.Nat,
    'friendlyName' : IDL.Text,
    'canisterId' : IDL.Text,
  });
  const Rule = IDL.Record({ 'id' : IDL.Nat, 'text' : IDL.Text });
  const Preferences = IDL.Record({
    'notes' : IDL.Text,
    'dApps' : IDL.Vec(PreferredDApp),
    'rules' : IDL.Vec(Rule),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const WorkflowId = IDL.Nat;
  const Owner = IDL.Principal;
  const Timestamp = IDL.Int;
  const Workflow = IDL.Record({
    'id' : WorkflowId,
    'owner' : Owner,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'updatedAt' : Timestamp,
    'planText' : IDL.Text,
    'favorite' : IDL.Bool,
  });
  const HistoryId = IDL.Nat;
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const ChatRole = IDL.Variant({ 'user' : IDL.Null, 'assistant' : IDL.Null });
  const ChatMessage = IDL.Record({
    'content' : IDL.Text,
    'role' : ChatRole,
    'timestamp' : Timestamp,
  });
  const Conversation = IDL.Record({ 'messages' : IDL.Vec(ChatMessage) });
  const PlanResult = IDL.Record({ 'planText' : IDL.Text });
  const HistoryEntry = IDL.Record({
    'id' : HistoryId,
    'owner' : Owner,
    'goal' : IDL.Text,
    'createdAt' : Timestamp,
    'planText' : IDL.Text,
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'addDApp' : IDL.Func([IDL.Text, IDL.Text], [Preferences], []),
    'addRule' : IDL.Func([IDL.Text], [Preferences], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createWorkflow' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text, IDL.Bool],
        [Workflow],
        [],
      ),
    'deleteDApp' : IDL.Func([IDL.Nat], [Preferences], []),
    'deleteHistoryEntry' : IDL.Func([HistoryId], [IDL.Bool], []),
    'deleteRule' : IDL.Func([IDL.Nat], [Preferences], []),
    'deleteWorkflow' : IDL.Func([WorkflowId], [IDL.Bool], []),
    'duplicateWorkflow' : IDL.Func([WorkflowId], [IDL.Opt(Workflow)], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'exportWorkflowMarkdown' : IDL.Func(
        [WorkflowId],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'generatePlan' : IDL.Func([IDL.Text, Conversation], [PlanResult], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getHistoryEntry' : IDL.Func(
        [HistoryId],
        [IDL.Opt(HistoryEntry)],
        ['query'],
      ),
    'getPreferences' : IDL.Func([], [IDL.Opt(Preferences)], ['query']),
    'getWorkflow' : IDL.Func([WorkflowId], [IDL.Opt(Workflow)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isOpenAIConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'listHistory' : IDL.Func([], [IDL.Vec(HistoryEntry)], ['query']),
    'listWorkflows' : IDL.Func([], [IDL.Vec(Workflow)], ['query']),
    'refinePlan' : IDL.Func([IDL.Text, Conversation], [PlanResult], []),
    'savePreferences' : IDL.Func([Preferences], [Preferences], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'searchWorkflows' : IDL.Func([IDL.Text], [IDL.Vec(Workflow)], ['query']),
    'setNotes' : IDL.Func([IDL.Text], [Preferences], []),
    'setOpenAIApiKey' : IDL.Func([IDL.Text], [], []),
    'toggleFavorite' : IDL.Func([WorkflowId], [IDL.Opt(Workflow)], []),
    'updateDApp' : IDL.Func([PreferredDApp], [Preferences], []),
    'updateRule' : IDL.Func([Rule], [Preferences], []),
    'updateWorkflow' : IDL.Func([Workflow], [IDL.Opt(Workflow)], []),
  });
};

export const init = ({ IDL }) => { return []; };