/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cell { 'value' : Value, 'name' : string }
export interface ChatMessage {
  'content' : string,
  'role' : ChatRole,
  'timestamp' : Timestamp,
}
export type ChatRole = { 'user' : null } |
  { 'assistant' : null };
export interface Conversation { 'messages' : Array<ChatMessage> }
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface HistoryEntry {
  'id' : HistoryId,
  'owner' : Owner,
  'goal' : string,
  'createdAt' : Timestamp,
  'planText' : string,
}
export type HistoryId = bigint;
export type Owner = Principal;
export interface PlanResult { 'planText' : string }
export interface Preferences {
  'notes' : string,
  'dApps' : Array<PreferredDApp>,
  'rules' : Array<Rule>,
}
export interface PreferredDApp {
  'id' : bigint,
  'friendlyName' : string,
  'canisterId' : string,
}
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export interface Rule { 'id' : bigint, 'text' : string }
export type Timestamp = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface Workflow {
  'id' : WorkflowId,
  'owner' : Owner,
  'name' : string,
  'createdAt' : Timestamp,
  'tags' : Array<string>,
  'description' : string,
  'updatedAt' : Timestamp,
  'planText' : string,
  'favorite' : boolean,
}
export type WorkflowId = bigint;
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'addDApp' : ActorMethod<[string, string], Preferences>,
  'addRule' : ActorMethod<[string], Preferences>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createWorkflow' : ActorMethod<
    [string, string, Array<string>, string, boolean],
    Workflow
  >,
  'deleteDApp' : ActorMethod<[bigint], Preferences>,
  'deleteHistoryEntry' : ActorMethod<[HistoryId], boolean>,
  'deleteRule' : ActorMethod<[bigint], Preferences>,
  'deleteWorkflow' : ActorMethod<[WorkflowId], boolean>,
  'duplicateWorkflow' : ActorMethod<[WorkflowId], [] | [Workflow]>,
  'execute' : ActorMethod<[string], Result>,
  'exportWorkflowMarkdown' : ActorMethod<[WorkflowId], [] | [string]>,
  'generatePlan' : ActorMethod<[string, Conversation], PlanResult>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getHistoryEntry' : ActorMethod<[HistoryId], [] | [HistoryEntry]>,
  'getPreferences' : ActorMethod<[], [] | [Preferences]>,
  'getWorkflow' : ActorMethod<[WorkflowId], [] | [Workflow]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isOpenAIConfigured' : ActorMethod<[], boolean>,
  'listHistory' : ActorMethod<[], Array<HistoryEntry>>,
  'listWorkflows' : ActorMethod<[], Array<Workflow>>,
  'refinePlan' : ActorMethod<[string, Conversation], PlanResult>,
  'savePreferences' : ActorMethod<[Preferences], Preferences>,
  'schema' : ActorMethod<[], string>,
  'searchWorkflows' : ActorMethod<[string], Array<Workflow>>,
  'setNotes' : ActorMethod<[string], Preferences>,
  'setOpenAIApiKey' : ActorMethod<[string], undefined>,
  'toggleFavorite' : ActorMethod<[WorkflowId], [] | [Workflow]>,
  'updateDApp' : ActorMethod<[PreferredDApp], Preferences>,
  'updateRule' : ActorMethod<[Rule], Preferences>,
  'updateWorkflow' : ActorMethod<[Workflow], [] | [Workflow]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];